export default [
  {
    id: 12,
    img: "https://banking-jet.vercel.app/icons/auth-image.svg",
    title: "Horizon Finance Dashboard ",
    desc: "A modern financial bank management dashboard.",
    tech: "Next14, Typescript, Appwrite, ShadCN, etc .",
    sourceCode: "https://github.com/ErgaAsDev/finance-bank-dashboard",
    linkCode: "https://banking-jet.vercel.app/sign-in",
    category: "Next",
  },
  {
    id: 13,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Google_Docs_2020_Logo.svg/1489px-Google_Docs_2020_Logo.svg.png",
    title: "LiveDocs",
    desc: "A collaborative editor like Google Docs.",
    tech: "Next14, Typescript, Liveblocks, Lexical Editor, ShadCN, Tailwind .",
    sourceCode: "https://github.com/ErgaAsDev/collaborative-editor-main",
    linkCode: "https://jsm-live-docs.vercel.app/sign-in",
    category: "Next",
  },
  {
    id: 14,
    img: "https://camo.githubusercontent.com/cd51bbe68f99cfd7fd2f9e9cf944cf515f514a26b855b8c8e7b21647a6b75611/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f64644b5138735a6f5f76382f302e6a7067",
    title: "Inventory App",
    desc: "An inventory management app.",
    tech: "Next14, Typescript, NodeJS, Prisma, Tailwind.",
    sourceCode: "https://github.com/ErgaAsDev/inventory-management-app",
    // linkCode: "https://jsm-live-docs.vercel.app/sign-in",
    category: "Next",
  },
  {
    id: 1,
    img: "https://buildwithangga.com/storage/assets/portfolio/HOiN8RbdRr7mdnNXIAeRejTVjDymzP8uIQH5dcHU.jpeg",
    title: "Furnature: furniture e-commerce",
    desc: "Created fully dynamic furniture e-commerce web pages with user authentification.",
    tech: "React (CRA) + context API, Styled component CSS, Stripe, Auth0.",
    sourceCode: "https://github.com/ErgaAsDev/furnature-project",
    linkCode: "https://erga-furnature-commerce.netlify.app/",
    category: "React",
  },
  {
    id: 3,
    img: "https://play-lh.googleusercontent.com/PCpXdqvUWfCW1mXhH1Y_98yBpgsWxuTSTofy3NGMo9yBTATDyzVkqU580bfSln50bFU",
    title: "Github User Tracks",
    desc: "Created an app to look up the detail information of GitHub Users using GitHub API with user authentification.",
    tech: "React (CRA) + context API, Styled component CSS, FusionChart, Auth0.",
    sourceCode: "https://github.com/ErgaAsDev/github-users-info",
    linkCode: "https://erga-github-users-search.netlify.app",
    category: "React",
  },
  {
    id: 4,
    img: "https://cdn.icon-icons.com/icons2/1488/PNG/512/5329-dribble_102570.png",
    title: "UIUX Portfolio",
    desc: "Designs that i have created so far..",
    tech: "Just Figma and few plugins",
    sourceCode:
      "https://ergastyle.notion.site/Erga-s-UIX-Portfolio-266f1d5e7d834606856e183aaf7c52f9",
    linkCode:
      "https://ergastyle.notion.site/Erga-s-UIX-Portfolio-266f1d5e7d834606856e183aaf7c52f9",
    category: "UIUX",
  },
  {
    id: 10,
    img: "https://www.telegraph.co.uk/content/dam/food-and-drink/2019/01/11/TELEMMGLPICT000185036503_trans_NvBQzQNjv4Bq8m3xuhMyFOjUOkuEnTdW-M-bhHwB87o-r13mliye62g.jpeg?imwidth=960",
    title: "Eat n Cook App",
    desc: "I created an cook recipes app with search feature and detail pages.",
    tech: "Vite, React, SCSS",
    sourceCode: "https://github.com/ErgaAsDev/cmlabs-frontend-fulltime-test",
    linkCode: "https://eatncook.netlify.app/",
    category: "React",
  },
  {
    id: 2,
    img: "https://assets.materialup.com/uploads/ceaae143-5c6c-4652-aa44-67068de4672a/preview.jpg",
    title: "Crypto Trading Landing Page",
    desc: "I created a crypto trading landing page using NextJS, designed in Figma.",
    tech: "Figma, Next.JS, Bootstrap",
    sourceCode: "https://github.com/ErgaAsDev/cryptoon-cryptopages",
    linkCode: "https://cryptoon-cryptopages.vercel.app/",
    category: "Next",
  },
  ,
  {
    id: 5,
    img: "https://d1fdloi71mui9q.cloudfront.net/WxTZNWsTQe908iLLG5RR_zy7kIGJgbi6U7RRN",
    title: "Cultigo Landing Page",
    desc: "I created a landing page for my friend's website profile company, designed in Figma.",
    tech: "Figma, Next.js, Tailwind CSS, SasS",
    linkCode: "https://nextjs-cultigo.vercel.app/",
    category: "Next",
  },
  {
    id: 90,
    img: "https://codenesia.id/storage/2022/03/react-native.png",
    title: "React Native - Jobshift",
    desc: "I created an app for job platform.",
    tech: "React Native (Expo)",
    sourceCode: "https://github.com/ErgaAsDev/reactnative_jobsift_1stProject",
    linkCode:
      "https://expo.dev/@ergaasdev/jobsift?serviceType=classic&distribution=expo-go",
    category: "React Native",
  },
  {
    id: 6,
    img: "https://cdn-icons-png.flaticon.com/512/2344/2344132.png",
    title: "Kalkulator Biaya Listrik",
    desc: "I created an app to calculate electricity daily, weekly and monthly expenses.",
    tech: "Vanilla Development (HTML, CSS, JavaScript",
    sourceCode: "https://github.com/ErgaAsDev/kalkulator-biaya-listrik",
    linkCode: "https://erga-kalkbiayalistrik.netlify.app/",
    category: "React",
  },
  {
    id: 7,
    img: "https://htmlcolorcodes.com/assets/images/color-picker/html-color-codes-color-wheel-complementary.svg",
    title: "Color Clicker",
    desc: "I created an app to generate random color using hex color.",
    tech: "Vanilla Development (HTML, CSS, JavaScript",
    sourceCode: "https://github.com/ErgaAsDev/color-clicker",
    linkCode: "https://erga-colorclicker.netlify.app/",
    category: "React",
  },
  {
    id: 8,
    img: "https://raw.githubusercontent.com/zakkariyaa/tenzies-game/db9fb6c857847c3508c4273b28ed375f90babbd3/src/assets/tenzi-react.png?raw=true",
    title: "Tenzie Game",
    desc: "I created a simple game where if all numbers are the same you win.",
    tech: "React, CSS",
    sourceCode: "https://github.com/ErgaAsDev/tenzie-game",
    linkCode: "https://erga-tenzie-game.netlify.app/",
    category: "React",
  },
];
