export default [
  {
    id: 1,
    img: "https://buildwithangga.com/storage/assets/portfolio/HOiN8RbdRr7mdnNXIAeRejTVjDymzP8uIQH5dcHU.jpeg",
    title: "Furnature: furniture e-commerce",
    desc: "Created fully dynamic furniture e-commerce web pages with user authentification.",
    tech: "React (CRA) + context API, Styled component CSS, Stripe, Auth0.",
    sourceCode: "https://github.com/ErgaAsDev/furnature-project",
    linkCode: "https://erga-furnature-commerce.netlify.app/",
  },
  {
    id: 3,
    img: "https://play-lh.googleusercontent.com/PCpXdqvUWfCW1mXhH1Y_98yBpgsWxuTSTofy3NGMo9yBTATDyzVkqU580bfSln50bFU",
    title: "Github User Tracks",
    desc: "Created an app to look up the detail information of GitHub Users using GitHub API with user authentification.",
    tech: "React (CRA) + context API, Styled component CSS, FusionChart, Auth0.",
    sourceCode: "https://github.com/ErgaAsDev/github-users-info",
    linkCode: "https://erga-github-users-search.netlify.app",
  },
  {
    id: 4,
    img: "https://mybayutcdn.bayut.com/mybayut/wp-content/uploads/bayut-sa-screenshotv3.jpg",
    title: "Realdeal: real estate website",
    desc: "Created functional and responsive real-estate website using Next with RapidAPI (bayut.com API).",
    tech: "Next.js (SSG and SSR), Chakra UI, RapidAPI.",
    sourceCode: "https://github.com/ErgaAsDev/realestate-realdeal",
    linkCode: "https://erga-microsoftpage.netlify.app/",
  },
  {
    id: 2,
    img: "https://assets.materialup.com/uploads/ceaae143-5c6c-4652-aa44-67068de4672a/preview.jpg",
    title: "Crypto Trading Landing Page",
    desc: "I created a crypto trading landing page using NextJS, designed in Figma.",
    tech: "Figma, Next.JS, Bootstrap",
    sourceCode: "https://github.com/ErgaAsDev/cryptoon-cryptopages",
    linkCode: "https://cryptoon-cryptopages.vercel.app/",
  },
  ,
  {
    id: 5,
    img: "https://d1fdloi71mui9q.cloudfront.net/WxTZNWsTQe908iLLG5RR_zy7kIGJgbi6U7RRN",
    title: "Cultigo Landing Page",
    desc: "I created a landing page for my friend's website profile company, designed in Figma.",
    tech: "Figma, Next.js, Tailwind CSS, SasS",
    linkCode: "https://nextjs-cultigo.vercel.app/",
  },
  {
    id: 6,
    img: "https://cdn-icons-png.flaticon.com/512/2344/2344132.png",
    title: "Kalkulator Biaya Listrik",
    desc: "I created an app to calculate electricity daily, weekly and monthly expenses.",
    tech: "Vanilla Development (HTML, CSS, JavaScript",
    sourceCode: "https://github.com/ErgaAsDev/kalkulator-biaya-listrik",
    linkCode: "https://erga-kalkbiayalistrik.netlify.app/",
  },
  {
    id: 7,
    img: "https://htmlcolorcodes.com/assets/images/color-picker/html-color-codes-color-wheel-complementary.svg",
    title: "Color Clicker",
    desc: "I created an app to generate random color using hex color.",
    tech: "Vanilla Development (HTML, CSS, JavaScript",
    sourceCode: "https://github.com/ErgaAsDev/color-clicker",
    linkCode: "https://erga-colorclicker.netlify.app/",
  },
  {
    id: 8,
    img: "https://raw.githubusercontent.com/zakkariyaa/tenzies-game/db9fb6c857847c3508c4273b28ed375f90babbd3/src/assets/tenzi-react.png?raw=true",
    title: "Tenzie Game",
    desc: "I created a simple game where if all numbers are the same you win.",
    tech: "React, CSS",
    sourceCode: "https://github.com/ErgaAsDev/tenzie-game",
    linkCode: "https://erga-tenzie-game.netlify.app/",
  },
  {
    id: 9,
    img: "https://i.imgflip.com/33rsw.jpg",
    title: "Meme Generator",
    desc: "I created an app to generate random memes, and can edit the texts.",
    tech: "Vite, React, CSS",
    sourceCode: "https://github.com/ErgaAsDev/meme-generator",
    linkCode: "https://erga-memegenerator.netlify.app/",
  },
  {
    id: 10,
    img: "https://miro.medium.com/max/924/1*8wNWIJh1hPBoGFxLrYlvUQ.png",
    title: "Random Quote",
    desc: "I created an app to generate random quote. and It is for FreeCodeCamp certification.",
    tech: "Vite, React, CSS",
    sourceCode: "https://github.com/ErgaAsDev/Random-quote",
    linkCode: "https://erga-random-quote.netlify.app/",
  },
];
